### ISSUE TITLE
homework review completed. 請參考issue調整。

### ISSUE THREAD

**Issue by hatelove** [resoft/ColumnSum#1]
## 建議調整項目
- 命名調整：UnitTest1 的命名不具備意義，test method 名稱也沒有帶出 scenario 的關鍵點。
- 未正確且清楚描述需求：在測試案例中，並未看到 11 筆資料的呈現。只看到 `new Table().Get()`，這樣子的測試案例無法讓閱讀的人知道，expected 為什麼是期望那樣的集合。
- API 的可用性調整：測試案例就是API的使用說明書，從測試案例看到，呼叫端如果要用 production code 的 API，得自己先把欄位（例如 Cost, Revenue）篩選出來，才可以使用 `SumList()` 的方法。設計API的過程，要考慮怎麼讓呼叫端最好用，在需求或未來異動程式碼時，可以讓 API 跟 production code 越穩定越好。當 API 設計地讓呼叫端越好用，往往也代表著 production code 設計的難度。
- 集合型別，該使用什麼樣的資料結構，也是可以思考的。並不是只有 `List<T>` 可以用。有時候使用 `IEnumerable<T>` 效能跟擴充性上更好。
- 寫法調整：`.Where(x => int.TryParse(x.val.ToString(), out number))` 這一行是極度極度糟糕的寫法，先把 val 轉成 string 再用 `int.TryParse()` 去處理，完全是人體程式碼混淆器的寫法。
- 這個需求乍看之下很像N筆一組的 grouping, 但其需求本質上是 Paging (分頁), 所以只需要用 `Skip()`, `Take()`, `Sum()` 就可以輕鬆完成這需求。
- products 測試資料的初始化，建議可以改成下列寫法，比起用 `List.Add()` 語意更清楚，寫起來更快速。

```
            var products = new List<Product>()
            {
                new Product() { Id=1 ,Cost=1 ,Revenue=11,SellPrice=21 },
                new Product() { Id=2 ,Cost=2 ,Revenue=12,SellPrice=22 },
            };
```
## 參考

可以參考一下我的 sample code: https://gist.github.com/hatelove/f5a4c2591293828b637f#file-getsumbypagesize_v2-cs

重點 focus 在下列幾點：
1. 呼叫端怎麼呼叫最好用, 語意清楚, 參數夠少, intellisense輔助。
2. API 在需求異動時，能越穩定越好，代表支援有足夠的彈性。在面對重構時，也不會影響到呼叫端的使用，例如 property rename。
3. 測試案例要怎麼呈現，最像口語化的描述著呼叫端使用情境。包含怎麼寫語意最清楚，寫起來最快。

這個 homework 基本上有四種方式來實作，也考驗著對 C# 的熟悉程度。
1. 使用 enum, production code 以 if/else 來分辨
2. 使用 string + reflection 來動態決定使用哪一個 property 加總
3. 使用 delegate/lambda 針對 Product 型別來處理
4. 使用 generic 支援泛型，使用 extension method 針對所有集合都提供這樣的功能

**Comment by resoft** [comment]
已依照建議調整
再麻煩91有空時再幫我review一下唷
thx

**Comment by hatelove** [comment]
great, 對於測試案例取得 11 筆 orders 的部分，還是建議可以再調整
